language: python
python: 3.5

sudo: false

env:
  matrix:
  - TOXENV=py27
  - TOXENV=py35

addons:
  apt:
    packages:
      - libdb-dev

install: pip install -U tox

script: tox

after_success:
  - bash <(curl -s https://codecov.io/bash)

#deploy:
  #provider: pypi
  #user: scrapy-plugins
  #distributions: sdist bdist_wheel
  #password:
    #secure: iKVlMlKSr+LOuCCMMOqL65aYjNRy3k1Zb4d7NRN0JpWS5DGau8G8cEhJ1dY4uyc/DNKVJmd939OiLBsUqqCmz09+ozen/YrRNjEZS5lOwBNfhpiCESkbOjcInV1PQgx2XfuHGp8O/9vxtXjjH9WE9CabQ+8Zg5/rMMvXizT4/O4=
  #on:
    #tags: true
    #all_branches: true
    #repo: scrapy-plugins/scrapy-deltafetch
    #condition: $TOXENV = py27
